In [40]:
import pandas as pd
import plotly.express as px

In [41]:
df = pd.read_csv(
    'C:/OD/OneDrive - OHLAGROUP/Desktop/Jonathan Miranda/PERSONAL/TRIPLETEN/Proyectos/Sprint 7/Proyecto_S7/vehicles_us.csv'
)

df.head()

,price,model_year,model,condition,cylinders,fuel,odometer,transmission,type,paint_color,is_4wd,date_posted,days_listed
0,9400,2011.0,bmw x5,good,6.0,gas,145000.0,automatic,SUV,NaN,1.0,2018-06-23,19
1,25500,NaN,ford f-150,good,6.0,gas,88705.0,automatic,pickup,white,1.0,2018-10-19,50
2,5500,2013.0,hyundai sonata,like new,4.0,gas,110000.0,automatic,sedan,red,NaN,2019-02-07,79
3,1500,2003.0,ford f-150,fair,8.0,gas,NaN,automatic,pickup,NaN,NaN,2019-03-22,9
4,14900,2017.0,chrysler 200,excellent,4.0,gas,80903.0,automatic,sedan,black,NaN,2019-04-02,28

In [42]:
df.shape

(51525, 13)

In [43]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 51525 entries, 0 to 51524
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   price         51525 non-null  int64
 1   model_year    47906 non-null  float64
 2   model         51525 non-null  str
 3   condition     51525 non-null  str
 4   cylinders     46265 non-null  float64
 5   fuel          51525 non-null  str
 6   odometer      43633 non-null  float64
 7   transmission  51525 non-null  str
 8   type          51525 non-null  str
 9   paint_color   42258 non-null  str
 10  is_4wd        25572 non-null  float64
 11  date_posted   51525 non-null  str
 12  days_listed   51525 non-null  int64
dtypes: float64(4), int64(2), str(7)
memory usage: 7.7 MB

In [44]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
price,51525.0,12132.464920,10040.803015,1.0,5000.0,9000.0,16839.0,375000.0
model_year,47906.0,2009.750470,6.282065,1908.0,2006.0,2011.0,2014.0,2019.0
cylinders,46265.0,6.125235,1.660360,3.0,4.0,6.0,8.0,12.0
odometer,43633.0,115553.461738,65094.611341,0.0,70000.0,113000.0,155000.0,990000.0
is_4wd,25572.0,1.000000,0.000000,1.0,1.0,1.0,1.0,1.0
days_listed,51525.0,39.554760,28.204270,0.0,19.0,33.0,53.0,271.0

In [45]:
df.isna().sum()

price               0
model_year       3619
model               0
condition           0
cylinders        5260
fuel                0
odometer         7892
transmission        0
type                0
paint_color      9267
is_4wd          25953
date_posted         0
days_listed         0
dtype: int64

In [46]:
df.duplicated().sum()

np.int64(0)

In [47]:
df_clean = df.dropna()

df_clean.isna().sum()

price           0
model_year      0
model           0
condition       0
cylinders       0
fuel            0
odometer        0
transmission    0
type            0
paint_color     0
is_4wd          0
date_posted     0
days_listed     0
dtype: int64

In [48]:
fig = px.histogram(
    df_clean,
    x='price',
    nbins=50,
    title='Distribución de precios'
)

fig.show()

In [57]:
fig = px.histogram(
    df_clean,
    x='odometer',
    nbins=50,
    title='Distribución del kilometraje'
)

fig.show()

In [50]:
df_clean['type'].value_counts()

type
truck          5470
SUV            5148
pickup         2867
wagon           633
sedan           329
offroad         128
hatchback        82
other            72
coupe            46
convertible      31
van              25
mini-van         21
Name: count, dtype: int64

In [51]:
fig = px.bar(
    df_clean['type'].value_counts(),
    title='Cantidad de vehículos por tipo'
)

fig.show()

In [52]:
df_clean['condition'].value_counts()

condition
excellent    7452
good         5552
like new     1329
fair          453
new            45
salvage        21
Name: count, dtype: int64

In [53]:
fig = px.bar(
    df_clean['condition'].value_counts(),
    title='Condición de los vehículos'
)

fig.show()

In [54]:
fig = px.scatter(
    df_clean,
    x='odometer',
    y='price',
    title='Precio vs Kilometraje'
)

fig.show()

In [55]:
fig = px.scatter(
    df_clean,
    x='model_year',
    y='price',
    title='Precio según año del vehículo'
)

fig.show()

In [56]:
fig = px.box(
    df_clean,
    x='type',
    y='price',
    title='Precio por tipo de vehículo'
)

fig.show()